from tkinter import *
window = Tk()
window.title("Miles to Kilometer converter")
window.minsize(200, 200)
window.config(padx=20, pady=20)
miles = Label(text="Miles")
miles.grid(row=0,column=2)
input_in_miles = Entry(width=20)
input_in_miles.grid(row=0,column=1)
converter = Label(text="is equal to")
converter.grid(row=1,column=0)
def convert_miles():
      input_miles = float(input_in_miles.get())
      km= round(input_miles * 1.609)
      result.config(text=f"{km}")
result = Label(text="0")
result.grid(row=1,column=1)
km = Label(text="km")
km.grid(row=1,column=2)
calc_button =Button(text="Calculate",command=convert_miles)
calc_button.grid(row=2,column=1)
window.mainloop()